### PR TITLE
fix mergeWith to keep 'falsy' properties from right side

### PR DESCRIPTION
**Pull request by hoschi**
Current code remove properties which are "falsy" like `0`.

### CODE REVIEW

**Comment by pirelenito** [comment]
We just faced the same problem in our project.

What was the original reason for removing props? It seems way too intrusive for a HOC to do that. Could we just get rid of that?

Btw, `react-component-queries` is awesome! @ctrlplusb ❤️

**Comment by ctrlplusb** [comment]
Apologies about this. Defo a bug.

Appreciate the PR, I'll look to merge this week if review is good.

**Comment by pirelenito** [comment]
Hi @ctrlplusb, did you had a chance to take a look at this? The failure in codecov is pretty weird... I couldn't understand where the coverage was reduced.

**Comment by ctrlplusb** [comment]
Apologies for the tardiness in getting to this.  All great. Thank you so much for the help!

**Comment by hoschi** [comment]
@ctrlplusb thanks for looking into my stuff :+1:

**Pull request merged**
